MEMORY
{
  RAM : ORIGIN = 0x40000000, LENGTH = 16M
  FLASH : ORIGIN = 0x20500000, LENGTH = 16M
  MEMLCD: ORIGIN = 0xB0000000, LENGTH = 32k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_STACK", RAM);
REGION_ALIAS("REGION_HEAP", RAM);

_lcdfb = ORIGIN(MEMLCD);
/* Size of the main kernel stack */
_stack_size = 16K;
_eheap = ORIGIN(RAM) + LENGTH(RAM);
